-- phpMyAdmin SQL Dump
-- version 4.1.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: 02. Jan 2014 um 16:33
-- Server Version: 5.6.15-log
-- PHP Version: 5.4.14

SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `joomla25x`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `#__allmediaplay_playerlist`
--

DROP TABLE IF EXISTS `#__allmediaplay_playerlist`;
CREATE TABLE IF NOT EXISTS `#__allmediaplay_playerlist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` varchar(8) NOT NULL,
  `location` varchar(25) NOT NULL,
  `code` mediumtext NOT NULL,
  `description` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  AUTO_INCREMENT=54 ;

--
-- Daten für Tabelle `#__allmediaplay_playerlist`
--

INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(1, '6.7', 'local', '<div id="{SOURCEID}" style="width:{WIDTH}px;height:{HEIGHT}px;" title="AllMediaPlay Player"></div>\r\n<script type="text/javascript">\r\n	jwplayer(''{SOURCEID}'').setup({\r\n		''file'': ''{SITEURL}/{FOLDER}/{SOURCE}.{FILE_EXT}'',\r\n		''image'': ''{PLAYER_POSTER_FRAME}'',\r\n		''height'': ''{HEIGHT}'',\r\n		''width'': ''{WIDTH}'',\r\n		''modes'': [\r\n			{ ''type'': ''html5'' },\r\n		  { ''type'': ''flash'', src: ''{PLUGIN_PATH}/includes/js/mediaplayer/jwplayer.flash.swf'' },\r\n		  { ''type'': ''download'' }\r\n		],\r\n		''autostart'': ''{PLAYER_AUTOPLAY}'',\r\n		''backcolor'': ''{PLAYER_BACKGROUND}'',\r\n		''plugins'': {\r\n			''viral-2'': {\r\n				''onpause'': ''false'',\r\n				''oncomplete'': ''true''\r\n			}\r\n		},\r\n		''controlbar'': ''{PLAYER_CONTROLBAR}'',\r\n		''skin'': ''{PLUGIN_PATH}/includes/js/mediaplayer/skins/{PLAYER_SKIN}/{PLAYER_SKIN}.xml''\r\n	});\r\n</script>\r\n', 'JW Player Video Local');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(2, '6.7', 'remote', '<div id="{SOURCEID}" style="width:{WIDTH}px;height:{HEIGHT}px;" title="AllMediaPlay Player"></div>\r\n<script type="text/javascript">\r\n	jwplayer(''{SOURCEID}'').setup({\r\n		''file'': ''{SOURCE}'',\r\n		''height'': ''{HEIGHT}'',\r\n		''width'': ''{WIDTH}'',\r\n		''modes'': [\r\n			{ type: ''html5'' },\r\n		  { type: ''flash'', src: ''{PLUGIN_PATH}/includes/js/mediaplayer/player.swf'' },\r\n		  { type: ''download'' }\r\n		],\r\n		''autostart'': ''{PLAYER_AUTOPLAY}'',\r\n		''backcolor'': ''{PLAYER_BACKGROUND}'',\r\n		''plugins'': {\r\n			''viral-2'': {\r\n				''onpause'': ''false'',\r\n				''oncomplete'': ''true''\r\n			}\r\n		},\r\n		''controlbar'': ''{PLAYER_CONTROLBAR}'',\r\n		''skin'': ''{PLUGIN_PATH}/includes/js/mediaplayer/skins/{PLAYER_SKIN}/{PLAYER_SKIN}.zip''\r\n	});\r\n</script>', 'JW Player Video Remote');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(3, '6.7', 'local', '<div id="{SOURCEID}" style="width:{WIDTH}px;height:{HEIGHT}px;" title="AllMediaPlay Player"></div>\r\n<script type=\\"text/javascript\\">\r\n	jwplayer(''{SOURCEID}'').setup({\r\n		''file'': ''{SITEURL}/{FOLDER}/{SOURCE}.{FILE_EXT}'',\r\n		''image'': ''{PLAYER_POSTER_FRAME}'',\r\n		''height'': ''{HEIGHT}'',\r\n		''width'': ''{WIDTH}'',\r\n		''modes'': [\r\n		  { ''type'': ''flash'', src: ''{PLUGIN_PATH}/includes/js/mediaplayer/player.swf'' },\r\n		  { ''type'': ''html5'' },\r\n		  { ''type'': ''download'' }\r\n		],\r\n		''autostart'': ''{PLAYER_AUTOPLAY}'',\r\n    ''backcolor'': ''{PLAYER_ABACKGROUND}'',\r\n    ''frontcolor'': ''{PLAYER_AFRONTCOLOR}'',\r\n    ''lightcolor'': ''{PLAYER_ALIGHTCOLOR}'',\r\n    ''controlbar'': ''bottom''\r\n	});\r\n</script>', 'JW Player Audio Local');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(4, '6.7', 'remote', '<div id="{SOURCEID}" style="width:{WIDTH}px;height:{HEIGHT}px;" title="AllMediaPlay Player"></div>\r\n<script type="text/javascript">\r\n	jwplayer(''{SOURCEID}'').setup({\r\n		''file'': ''{SOURCE}.{FILE_EXT}'',\r\n		''height'': ''{HEIGHT}'',\r\n		''width'': ''{WIDTH}'',\r\n		''modes'': [\r\n		  { type: ''flash'', src: ''{PLUGIN_PATH}/includes/js/mediaplayer/player.swf'' },\r\n		  { type: ''html5'' },\r\n		  { type: ''download'' }\r\n		],\r\n		''autostart'': ''{PLAYER_AUTOPLAY}'',\r\n    ''backcolor'': ''{PLAYER_ABACKGROUND}'',\r\n    ''frontcolor'': ''{PLAYER_AFRONTCOLOR}'',\r\n    ''lightcolor'': ''{PLAYER_ALIGHTCOLOR}'',\r\n    ''controlbar'': ''bottom''\r\n	});\r\n</script>', 'JW Player Audio Remote');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(6, '', 'remote', '<script type=\\"text/javascript\\">\r\n	QT_WriteOBJECT_XHTML(''{SOURCE}'', ''{WIDTH}'', ''{HEIGHT}'', '''', ''autoplay'', ''{PLAYER_AUTOPLAY}'', ''bgcolor'', ''{PLAYER_BACKGROUNDQT}'', ''scale'', ''aspect'');\r\n</script>', 'Quicktime Video Remote');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(7, '', 'local', '<div id=\\"allmediaplayID_{SOURCEID}\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" title=\\"JoomlaWorks AllVideos Player\\"></div>\r\n<script type=\\"text/javascript\\">\r\n	var cnt = document.getElementById(''avID_{SOURCEID}'');\r\n	var src = ''{PLUGIN_PATH}/includes/js/wmvplayer/wmvplayer.xaml'';\r\n	var cfg = {\r\n		''file'': ''{SITEURL}/{FOLDER}/{SOURCE}.{FILE_EXT}'',\r\n		''image'': ''{PLAYER_POSTER_FRAME}'',\r\n		''width'': ''{WIDTH}'',\r\n		''height'': ''{HEIGHT}'',\r\n		''autostart'': ''{PLAYER_AUTOPLAY}''\r\n	};\r\n	var ply = new jeroenwijering.Player(cnt,src,cfg);\r\n</script>', 'Windows Media Local');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(8, '', 'remote', '<div id=\\"allmediaplayID_{SOURCEID}\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" title=\\"JoomlaWorks AllVideos Player\\"></div>\r\n<script type=\\"text/javascript\\">\r\n	var cnt = document.getElementById(''avID_{SOURCEID}'');\r\n	var src = ''{PLUGIN_PATH}/includes/js/wmvplayer/wmvplayer.xaml'';\r\n	var cfg = {\r\n		''file'': ''{SOURCE}'',\r\n		''width'': ''{WIDTH}'',\r\n		''height'': ''{HEIGHT}'',\r\n		''autostart'': ''{PLAYER_AUTOPLAY}''\r\n	};\r\n	var ply = new jeroenwijering.Player(cnt,src,cfg);\r\n</script>', 'Windows Media Remote');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(9, '', 'local', '<object classid="clsid:67DABFBF-D0AB-41fa-9C46-CC0F21721616" width={WIDTH} height={HEIGHT} codebase="http://go.divx.com/plugin/DivXBrowserPlugin.cab">\r\n  <param name="custommode" value="none" />\r\n  <param name="previewImage" value="" />\r\n  <param name="autoPlay" value="false" />\r\n  <param name="bufferingMode" value="auto">  \r\n  <param name="src" value="{SITEURL_ABS}/{FOLDER}/{SOURCE}.{FILE_EXT}" />\r\n<embed type="video/divx" src="{SITEURL_ABS}/{FOLDER}/{SOURCE}.{FILE_EXT}" custommode="none" width={WIDTH} height={HEIGHT} bufferingMode="auto" autoPlay="false" previewImage="" pluginspage="http://go.divx.com/plugin/download/">\r\n</embed>\r\n</object>\r\n<!-- leaving the code below will help search index your video -->\r\n<!--<br />\r\nNo video? Get the DivX Web Player for <a style="text-decoration: underline;" href="http://download.divx.com/player/DivXWebPlayerInstaller.exe">Windows</a> or <a style="text-decoration: underline;" href="http://download.divx.com/player/DivXWebPlayer.dmg">Mac</a>-->', 'DivX Local');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(10, '', 'remote', '<object classid="clsid:67DABFBF-D0AB-41fa-9C46-CC0F21721616"\r\nwidth={WIDTH} height={HEIGHT}\r\ncodebase="http://go.divx.com/plugin/DivXBrowserPlugin.cab">\r\n  <param name="custommode" value="none" />\r\n  <param name="previewImage" value="" />\r\n  <param name="autoPlay" value="{PLAYER_AUTOPLAY}" />\r\n  <param name="bufferingMode" value="auto">  \r\n  <param name="src" value="{SOURCE}.{FILE_EXT}" />\r\n<embed type="video/divx" \r\nsrc="{SOURCE}.{FILE_EXT}" \r\ncustommode="none" \r\nwidth={WIDTH} \r\nheight={HEIGHT} \r\nbufferingMode="auto" \r\nautoPlay="{PLAYER_AUTOPLAY}" \r\npreviewImage="" \r\npluginspage="http://go.divx.com/plugin/download/">\r\n</embed>\r\n</object>\r\n<!-- leaving the code below will help search index your video -->\r\n<!--<br />\r\nNo video? Get the DivX Web Player for <a style="text-decoration: underline;" href="http://download.divx.com/player/DivXWebPlayerInstaller.exe">Windows</a> or <a style="text-decoration: underline;" href="http://download.divx.com/player/DivXWebPlayer.dmg">Mac</a>-->', 'DivX Remote');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(11, '', 'local', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"{SITEURL}/{FOLDER}/{SOURCE}.swf\\">\r\n	<param name=\\"movie\\" value=\\"{SITEURL}/{FOLDER}/{SOURCE}.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n</object>', 'SWF Local');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(12, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"{SOURCE}\\">\r\n	<param name=\\"movie\\" value=\\"{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n</object>', 'SWF Remote');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(13, '', 'remote', '<iframe src="http://www.youtube.com/embed/{SOURCE}" width="{WIDTH}" height="{HEIGHT}" frameborder="0" allowfullscreen title="AllMediaPlay Player"></iframe>', 'Youtube');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(14, '', 'remote', '<iframe src=\\"http://player.vimeo.com/video/{SOURCE}\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" frameborder=\\"0\\" title=\\"AllMediaPlay Player\\"></iframe>', 'Vimeo');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(15, '', 'remote', '<iframe src=\\"http://www.dailymotion.com/embed/video/{SOURCE}\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" frameborder=\\"0\\" title=\\"AllMediaPlay Player\\"></iframe>', 'DailyMotion');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(16, '', 'remote', '<script type=\\"text/javascript\\">\r\n	allmediaplay.ready(function(){\r\n		allmediaplay.embed({\r\n			''url'': ''http://blip.tv/oembed/?callback=bliptv{SOURCEID}&width={WIDTH}&height={HEIGHT}&url={SOURCE}'',\r\n			''callback'': ''bliptv{SOURCEID}'',\r\n			''playerID'': ''avID_{SOURCEID}''\r\n		});\r\n	});\r\n</script>\r\n<div id=\\"allmediaplayID_{SOURCEID}\\" title=\\"AllMediaPlay Player\\">&nbsp;</div>', 'Blip TV');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(17, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.123video.nl/123video_emb.swf?mediaSrc={SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.123video.nl/123video_emb.swf?mediaSrc={SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n</object>', '123Video');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(18, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://api.aniboom.com/e/{SOURCE}\\" title=\\"AllMEdiaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://api.aniboom.com/e/{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"sameDomain\\" />\r\n</object>', 'AniBoom');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(19, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.collegehumor.com/moogaloop/moogaloop.swf?clip_id={SOURCE}&use_node_id=true&fullscreen=1\\" title=\\"JoomlaWorks AllVideos Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.collegehumor.com/moogaloop/moogaloop.swf?clip_id={SOURCE}&use_node_id=true&fullscreen=1\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'CollegeHumor');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(20, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.flickr.com/apps/video/stewart.swf?v=109786\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.flickr.com/apps/video/stewart.swf?v=109786\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashvars\\" value=\\"intl_lang=en-us&amp;div_id=stewart_swf{SOURCE}_div&amp;flickr_notracking=true&amp;flickr_target=_self&amp;flickr_h={HEIGHT}&amp;flickr_w={WIDTH}&amp;flickr_no_logo=true&amp;onsite=true&amp;flickr_noAutoPlay=false&amp;in_photo_gne=true&amp;photo_secret=&amp;photo_id={SOURCE}&amp;flickr_doSmall=true\\" />\r\n</object>', 'flickr');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(21, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://player.ordienetworks.com/flash/fodplayer.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://player.ordienetworks.com/flash/fodplayer.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashvars\\" value=\\"key={SOURCE}\\" />\r\n</object>', 'funnyordie');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(22, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://media.mtvnservices.com/mgid:moses:video:gametrailers.com:{SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://media.mtvnservices.com/mgid:moses:video:gametrailers.com:{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"sameDomain\\" />\r\n	<param name=\\"base\\" value=\\".\\" />\r\n	<param name=\\"flashvars\\" value=\\"\\" />\r\n</object>', 'gametrailers');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(23, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{VWIDTH}px;height:{VHEIGHT}px;\\" data=\\"http://www.goal4replay.net/videoEmbedLa.swf?ID={AVSOURCE}&amp;MediaID=1\\">\r\n	<param name=\\"movie\\" value=\\"http://www.goal4replay.net/videoEmbedLa.swf?ID={AVSOURCE}&amp;MediaID=1\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'goal4replay');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(24, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://media.salemwebnetwork.com/godtube/resource/mediaplayer/5.6/player.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://media.salemwebnetwork.com/godtube/resource/mediaplayer/5.6/player.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashvars\\" value=\\"file=http://www.godtube.com/resource/mediaplayer/{SOURCE}.file&image=http://www.godtube.com/resource/mediaplayer/{SOURCE}.jpg&screencolor=000000&type=video&autostart={PLAYER_AUTOPLAY}&playonce=true&skin=http://media.salemwebnetwork.com/godtube/resource/mediaplayer/skin/default/videoskin.swf&logo.file=undefinedtheme/default/media/embed-logo.png&logo.link=http://www.godtube.com/watch/%3Fv%3D{SOURCE}&logo.position=top-left&logo.hide=false&controlbar.position=over\\" />\r\n</object>', 'godtube');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(25, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://video.google.com/googleplayer.swf?docid={SOURCE}&hl=en&fs=true\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://video.google.com/googleplayer.swf?docid={SOURCE}&hl=en&fs=true\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'Google Video');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(26, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://static.grindtv.com/player/optics.swf?sa=1&si=1&i={SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://static.grindtv.com/player/optics.swf?sa=1&si=1&i={SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'GrindTV');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(27, '', 'remote', '<script type=\\"text/javascript\\">\r\n	allmediaplay.ready(function(){\r\n		allmediaplay.embed({\r\n			''url'': ''http://api.justin.tv/api/embed/from_url.json?jsonp=justintv{SOURCEID}&width={WIDTH}&height={HEIGHT}&url={SOURCE}'',\r\n			''callback'': ''justintv{SOURCEID}'',\r\n			''playerID'': ''avID_{SOURCEID}''\r\n		});\r\n	});\r\n</script>\r\n<div id=\\"allmediaplayID_{SOURCEID}\\" title=\\"AllMediaPlay Player\\">&nbsp;</div>', 'Justin');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(28, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://sll.kewego.com/swf/kp.swf\\" title=\\"AllMediaPlay Player\\" name=\\"kplayer_{SOURCE}\\" id=\\"kplayer_{SOURCE}\\">\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashVars\\" value=\\"language_code=en&playerKey=902e0deec887&configKey=&suffix=&sig={SOURCE}&autostart={PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"movie\\" value=\\"http://sll.kewego.com/swf/kp.swf\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<video id=\\"kewego_HTML5_{SOURCE}\\" poster=\\"http://api.kewego.com/video/getHTML5Thumbnail/?playerKey=902e0deec887&amp;sig={SOURCE}\\" controls=\\"true\\" height=\\"{HEIGHT}\\" width=\\"{WIDTH}\\" preload=\\"none\\">\r\n		<source src=\\"http://api.kewego.com/video/getHTML5Stream/?playerKey=902e0deec887&amp;sig={SOURCE}\\" type=\\"video/mp4\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" />\r\n	</video>\r\n</object>', 'Kewego');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(29, '', 'remote', '<script data-vid=\\"{SOURCE}\\" src=\\"//player.ku6.com/out/v.js\\" data-width=\\"{WIDTH}\\" data-height=\\"{HEIGHT}\\"></script>', 'ku6 (China)');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(30, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.liveleak.com/e/{SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.liveleak.com/e/{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'liveleak');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(31, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.livevideo.com/flvplayer/embed/{SOURCE}&autoStart={PLAYER_AUTOPLAY}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.livevideo.com/flvplayer/embed/{SOURCE}&autoStart={PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'livevideo');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(32, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.metacafe.com/fplayer/{SOURCE}.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.metacafe.com/fplayer/{SOURCE}.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'metacafe');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(33, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://mediaservices.myspace.com/services/media/embed.aspx/m={SOURCE},t=1,mt=video\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://mediaservices.myspace.com/services/media/embed.aspx/m={SOURCE},t=1,mt=video\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"sameDomain\\" />\r\n</object>', 'MySpace');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(34, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.myvideo.de/movie/{SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.myvideo.de/movie/{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'MyVideo');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(35, '', 'remote', '<iframe src=\\"http://videos.sapo.pt/playhtml?file=http://rd3.videos.sapo.pt/{SOURCE}/mov/1\\" frameborder=\\"0\\" scrolling=\\"no\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" title=\\"AllMediaPlay Player\\"></iframe>', 'Sapo');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(36, '', 'remote', '<iframe src=\\"http://www.screenr.com/embed/{SOURCE}\\" frameborder=\\"0\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" title=\\"AllMEdiaPlay Player\\"></iframe>', 'Screenr');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(37, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.sevenload.com/pl/{SOURCE}/445x364/swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.sevenload.com/pl/{SOURCE}/445x364/swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'Sevenload');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(38, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://share.vrs.sohu.com/my/v.swf&id={SOURCE}&skinNum=2&topBar=1\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://share.vrs.sohu.com/my/v.swf&id={SOURCE}&skinNum=2&topBar=1\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"Always\\" />\r\n</object>', 'Schu (China)');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(39, '', 'remote', '<script type=\\"text/javascript\\">\r\n	allmediaplay.ready(function(){\r\n		allmediaplay.embed({\r\n			''url'': ''http://soundcloud.com/oembed?format=js&iframe=true&callback=soundcloud{SOURCEID}&auto_play={PLAYER_AUTOPLAY}&maxwidth={WIDTH}&url={SOURCE}'',\r\n			''callback'': ''soundcloud{SOURCEID}'',\r\n			''playerID'': ''avID_{SOURCEID}''\r\n		});\r\n	});\r\n</script>\r\n<div id=\\"allmediaplayID_{SOURCEID}\\" title=\\"AllMediaPlay Player\\">&nbsp;</div>', 'SoundCloud');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(40, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://media.mtvnservices.com/mgid:cms:item:southparkstudios.com:{SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://media.mtvnservices.com/mgid:cms:item:southparkstudios.com:{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'SouthPark (Clips only)');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(41, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://images.stupidvideos.com/2.0.2/swf/video.swf?sa=1&sk=7&si=2&i={SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://images.stupidvideos.com/2.0.2/swf/video.swf?sa=1&sk=7&si=2&i={SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'StupidVideos');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(42, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://my.voped.com/flash/vopedmainplayer.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://my.voped.com/flash/vopedmainplayer.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashvars\\" value=\\"oid=132&vid={SOURCE}&player=98&pt=1&at=2&aid=4ffca50b272e7\\" />\r\n</object>', 'tnaondemand');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(43, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.tudou.com/v/{SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.tudou.com/v/{SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'tudou');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(44, '', 'remote', '<iframe src=\\"http://www.twitvid.com/embed.php?guid={SOURCE}\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" frameborder=\\"0\\" title=\\"AllMediaPlay Player\\"></iframe>', 'twitvid.com');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(45, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.ustream.tv/flash/viewer.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.ustream.tv/flash/viewer.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashVars\\" value=\\"loc=%2F&amp;autoplay={PLAYER_AUTOPLAY}&amp;vid={SOURCE}&amp;locale=en_US&amp;hasticket=false&amp;v3=1\\" />\r\n</object>', 'ustream');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(46, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://i47.vbox7.com/player/ext.swf?vid={SOURCE}\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://i47.vbox7.com/player/ext.swf?vid={SOURCE}\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'vbox7');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(47, '', 'remote', '<iframe src=\\"http://veevr.com/embed/{SOURCE}\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" frameborder=\\"0\\" scrolling=\\"no\\" title=\\"AllMediaPlay Player\\"></iframe>', 'veevr');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(48, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.veoh.com/swf/webplayer/WebPlayer.swf?version=&permalinkId={SOURCE}&player=videodetailsembedded&videoAutoPlay={PLAYER_AUTOPLAY}&id=anonymous\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.veoh.com/swf/webplayer/WebPlayer.swf?version=&permalinkId={SOURCE}&player=videodetailsembedded&videoAutoPlay={PLAYER_AUTOPLAY}&id=anonymous\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n</object>', 'veoh');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(49, '', 'remote', '<iframe src=\\"http://www.vidiac.com/video/{SOURCE}/player?layout=&read_more=1\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" frameborder=\\"0\\" scrolling=\\"no\\" title=\\"AllMEdiaPlay Player\\"></iframe>', 'vidiac');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(50, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://d.yimg.com/nl/vyc/site/player.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://d.yimg.com/nl/vyc/site/player.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashvars\\" value=\\"vid={SOURCE}&amp;autoPlay={PLAYER_AUTOPLAY}&amp;volume=100&amp;enableFullScreen=1\\" />\r\n</object>', 'Yahoo');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(51, '', 'remote', '<iframe src=\\"http://yfrog.com/{SOURCE}:embed\\" width=\\"{WIDTH}\\" height=\\"{HEIGHT}\\" frameborder=\\"0\\" title=\\"AllMediaPlay Player\\"></iframe>', 'yfrog');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(52, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://player.youku.com/player.php/sid/{SOURCE}/v.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://player.youku.com/player.php/sid/{SOURCE}/v.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"sameDomain\\" />\r\n</object>', 'youku (China)');
INSERT INTO `#__allmediaplay_playerlist` (`id`, `version`, `location`, `code`, `description`) VALUES(53, '', 'remote', '<object type=\\"application/x-shockwave-flash\\" style=\\"width:{WIDTH}px;height:{HEIGHT}px;\\" data=\\"http://www.youmaker.com/v.swf\\" title=\\"AllMediaPlay Player\\">\r\n	<param name=\\"movie\\" value=\\"http://www.youmaker.com/v.swf\\" />\r\n	<param name=\\"quality\\" value=\\"high\\" />\r\n	<param name=\\"wmode\\" value=\\"{PLAYER_TRANSPARENCY}\\" />\r\n	<param name=\\"bgcolor\\" value=\\"{PLAYER_BACKGROUND}\\" />\r\n	<param name=\\"autoplay\\" value=\\"{PLAYER_AUTOPLAY}\\" />\r\n	<param name=\\"allowfullscreen\\" value=\\"true\\" />\r\n	<param name=\\"allowscriptaccess\\" value=\\"always\\" />\r\n	<param name=\\"flashvars\\" value=\\"file=http://www.youmaker.com/video/v/nu/{SOURCE}.xml&showdigits=true&overstretch=fit&autostart={PLAYER_AUTOPLAY}&linkfromdisplay=false&rotatetime=12&repeat=list&shuffle=false&showfsbutton=false&fsreturnpage=&fullscreenpage=\\" />\r\n</object>', 'youmaker');

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `#__allmediaplay_taglist`
--

DROP TABLE IF EXISTS `#__allmediaplay_taglist`;
CREATE TABLE IF NOT EXISTS `#__allmediaplay_taglist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `player_id` int(11) NOT NULL,
  `plist` int(1) NOT NULL,
  `name` varchar(30) NOT NULL,
  `description` varchar(255) NOT NULL,
  `ext` varchar(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  AUTO_INCREMENT=58 ;

--
-- Daten für Tabelle `#__allmediaplay_taglist`
--

INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(1, 1, 1, 'flv', 'FLV', 'flv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(2, 2, 1, 'flvremote', 'FLV Remote', 'flv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(3, 1, 1, 'mp4', 'MP4', 'mp4');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(4, 2, 1, 'mp4remote', 'MP4 Remote', 'mp4');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(5, 1, 0, 'ogv', 'OGV', 'ogv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(6, 2, 0, 'ogvremote', 'OGV Remote', 'ogv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(7, 1, 0, 'webm', 'WEBM', 'webm');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(8, 2, 0, 'webmremote', 'WEBM Remote', 'webm');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(9, 1, 0, 'f4v', 'F4V', 'f4v');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(10, 2, 0, 'f4vremote', 'F4V Remote', 'f4v');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(11, 1, 0, 'm4v', 'M4V', 'm4v');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(12, 2, 0, 'm4vremote', 'M4V Remote', 'm4v');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(13, 1, 0, '3gp', '3GP', '3gp');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(14, 2, 0, '3gpremote', '3GP Remote', '3gp');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(15, 1, 0, '3g2', '3G2', '3g2');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(16, 2, 0, '3g2remote', '3G2 Remote', '3g2');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(17, 3, 0, 'mp3', 'MP3', 'mp3');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(18, 4, 0, 'mp3remote', 'MP3 Remote', 'mp3');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(19, 3, 0, 'aac', 'AAC', 'aac');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(20, 4, 0, 'aacremote', 'AAC Remote', 'aac');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(21, 3, 0, 'm4a', 'M4A', 'm4a');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(22, 4, 0, 'm4aremote', 'M4A Remote', 'm4a');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(23, 3, 0, 'ogg', 'OGG', 'ogg');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(24, 4, 0, 'oggremote', 'OGG Remote', 'ogg');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(25, 1, 0, 'mov', 'MOV', 'mov');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(26, 6, 0, 'movremote', 'MOV Remote', 'mov');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(27, 1, 0, 'mpeg', 'MPEG', 'mpeg');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(28, 6, 0, 'mpegremote', 'MPEG Remote', 'mpeg');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(29, 1, 0, 'mpg', 'MPG', 'mpg');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(30, 6, 0, 'mpgremote', 'MPG Remote', 'mpg');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(31, 9, 0, 'avi', 'AVI', 'avi');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(32, 10, 0, 'aviremote', 'AVI Remote', 'avi');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(33, 7, 0, 'wmv', 'WMV', 'wmv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(34, 8, 0, 'wmvremote', 'WMV Remote', 'wmv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(35, 7, 0, 'wma', 'WMA', 'wma');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(36, 8, 0, 'wmaremote', 'WMA Remote', 'wma');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(37, 9, 0, 'divx', 'DIVX', 'divx');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(38, 10, 0, 'divxremote', 'DIVX Remote', 'divx');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(39, 11, 0, 'swf', 'SWF', 'swf');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(40, 12, 0, 'swfremote', 'SWF Remote', 'swf');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(41, 13, 0, 'youtube', 'Youtube', '');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(42, 14, 0, 'vimeo', 'Vimeo', '');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(43, 15, 0, 'dailymotion', 'DailyMotion', '');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(44, 16, 0, 'blib', 'Blip TV', '');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(45, 17, 0, '123video', '123Video', '');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(56, 9, 0, 'mkv', 'Matroska Media Container', 'mkv');
INSERT INTO `#__allmediaplay_taglist` (`id`, `player_id`, `plist`, `name`, `description`, `ext`) VALUES(57, 10, 0, 'mkvremote', 'Matroska Media Container Remote', 'mkv');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
